version: "3.8"
services:
  postgres-file:
    image: postgres:15
    environment:
      POSTGRES_DB: filestorage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - filedata:/var/lib/postgresql/data

  file-storage:
    build:
      context: .
      dockerfile: FileStoringService/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres-file;Port=5432;Database=filestorage;Username=postgres;Password=postgres"
    ports:
      - "8080:80"      # expose FileStoringService on port 8080
    depends_on:
      - postgres-file
    volumes:
      - ./storage:/app/Storage

  postgres-analysis:
    image: postgres:15
    environment:
      POSTGRES_DB: fileanalysis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - analysisdata:/var/lib/postgresql/data

  file-analysis:
    build:
      context: .
      dockerfile: FileAnalysisService/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres-analysis;Port=5432;Database=fileanalysis;Username=postgres;Password=postgres"
      FileStoringService__BaseUrl: "http://file-storage:80/api/files"
    ports:
      - "8081:80"     
    depends_on:
      - postgres-analysis
      - file-storage
    volumes:
      - ./wwwroot:/app/wwwroot

  kong-database:
    image: postgres:15
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
    volumes:
      - kongdata:/var/lib/postgresql/data

  kong-migrations:
    image: kong:3.0
    command: "kong migrations bootstrap"
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
    depends_on:
      - kong-database

  kong:
    image: kong:3.0
    environment:
      KONG_DATABASE: "off"
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
      KONG_DECLARATIVE_CONFIG: "/etc/kong/kong.yml"
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - "8000:8000"   # proxy
      - "8001:8001"   # admin API
    volumes:
      - ./kong/kong.yml:/etc/kong/kong.yml
    depends_on:
      - kong-migrations

volumes:
  filedata:
  analysisdata:
  kongdata:
